services:
  - type: web                      # Defines the service type as a web service
    name: cherryfrontend            # The service name in Render
    env: node                       # Node.js environment

    branch: main                    # Specifies the branch to auto-deploy
    autoDeploy: true                # Automatically deploy when new commits are pushed to 'main'

    # Build and start commands
    buildCommand: npm install && npm run build
    startCommand: npm start

    # Ensure Render publishes the 'build' directory
    publish:
      path: ./build

    plan: free                      # Specifies the free plan; adjust as needed
    healthCheckPath: /              # Health check endpoint

    pullRequestPreviewsEnabled: true  # Enables PR previews for other branches

    envVars:                        # Environment variables for production
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://api.cherryfrontend.com

    runtime: node 16                # Specify the Node.js runtime version
    region: oregon                  # Specify the region for deployment
